### ISSUE TITLE
preview feature not working lately

### ISSUE THREAD

**Issue by UmbraVivens** [NightLancer/PixivPreview#15]
looks like the script's preview feature isn't working over R18 thumbnails (of multi image posts specifically) in certain pages such as:

- the horizontal list under posts, which contains that artist's entire other works
- the frontpage
- when viewing an artist page (*/users/######)

however it works in my followed artists feed, it's been a few days like this
here is an example of the first bullet point
![image](https://user-images.githubusercontent.com/54699529/122154503-03040a00-ce1a-11eb-9f77-5da52ea8db00.png)
![image](https://user-images.githubusercontent.com/54699529/122154594-2f1f8b00-ce1a-11eb-827c-0e94498a5d73.png)

also, the preview only shows a single image, regardless of R18 or not, when used within a user's profile preview (which appears when hovering over a username or avatar)
![image](https://user-images.githubusercontent.com/54699529/122155524-fc769200-ce1b-11eb-8f69-09dd1f4d7c84.png)

**Comment by NightLancer** [comment]
Yes, there is a bug with all R18 multi image posts in "new" pixiv layout(it works on Daily rankings, for example). Thank you for reporting it. Fixed, will release update soon.

> also, the preview only shows a single image

Added multiple image preview for new layout page case(where number of pages are displayed over mini-preview), will be in update as well. 

As for "old" style pages(discovery, rankings, etc) - there no such counter over image, but I may do extra call for obtaining that counter, it takes ~1 second (for ~8000 km distance). So, for now, on such pages, there is no-delay single preview of users profile card. Would it be useful to implement such feature on "old" pages as well, regarding there may be ~1sec extra delay before showing the multiple images preview? If so, I can make such feature for the rest of the pages too(using one extra query).

**Comment by NightLancer** [comment]
@UmbraVivens any suggestions regarding last question? If none - I'm closing this issue as resolved.

**Comment by UmbraVivens** [comment]
oh right, yeah sure, maybe add it as a toggle in the corner menu
