### ISSUE TITLE
Can't Preview Image Sets of 4 or 5 files.

### ISSUE THREAD

**Issue by drakom88** [NightLancer/PixivPreview#17]
*Fixed after disabling Chrome's webpage translator.
Hello again,

Sorry to blemish your issues section once more.
When I try previewing an image set of 4 or 5 files, the preview panel either doesn't show at all (95%) or has a small black rectangle (5%). Other sizes of image sets preview correctly.
I have disabled other scripts, extensions, etc., turned off Google translate, to no avail.
For a while I have thought it was to do with collective image set file sizes, but have narrowed it down to this.

Thanks for any guidance in this matter.

**Comment by NightLancer** [comment]
@drakom88 Hello. 
Don't worry about it, this section exists for that very purpose)
I have some assumptions under which circumstances this might happen, but need some info to clarify it: 
- what is your preview script settings
- what is your screen size(in pixels)
- on which exact pages this issue occurs(or it is general issue)
- does refreshing same page helps or not

So, in case of 3 or 6 arts all works normally? If you resize your browser window a bit on 4-5 arts does it help?
And it would help if you provided some problematic artwork id(or link) so I could test it by myself.

Pixiv has changed the Discovery page and some users say that they have new "Following" page as well, but I still have an old version. I doubt it's the case, but I need to ensure that you have same page layouts as me. And in any case, how long approximately this problem persists? I somewhat changed logic of preview with delay to make less impact on users CPU, but it would rather work at 100% or not work at all(I tested it and it worked at that moment). But there is some chance there is a bug somewhere, so can you check [2.53.9](https://github.com/NightLancer/PixivPreview/raw/d4098857d90059d67626a6d2c16dbbb9cd04d350/PixivPreview.user.js) version if it has same bug? That version doesn't work on new Discovery page but there are still other pages to test.

**Comment by drakom88** [comment]
![Pix Sett](https://user-images.githubusercontent.com/64705714/141151124-1cec56eb-b20e-4ad7-bf94-725fcb865b09.png)

2560x1440, Chrome, zoom at 175%
I typically only use on a user's illustration/manga page, I just restarted PC and now 4-5 arts are working fine, but eventually they stop loading. I will post results from other sources when the problem comes up again.
Refreshing doesn't usually help, it has very rarely. 

Yes, every other number of arts functions well.

Okay, within 5 minutes of restart the problem is occurring. Umm, I will try to find SFW links.

Currently, I can preview this 4 arts from the user's Illustrations page:
https://www.pixiv.net/en/artworks/86867820
(Bottom of page 2 of user's Illustrations page.)

Now, after clicking through other artworks for 2-3 minutes, I come back to that same 4 arts on the Illustrations page and it will not preview, either won't load or small black rectangle when I click to preview.

Installed 2.53.9, issue persists.

*edit* 
Have had the issue for 3 months at least. 
I'm not very familiar with Discovery or Following pages.

*edit 2*
Looks like I was wrong. This 23 arts is also failing to preview. (Bottom of page 1 user's Illustrations page)
https://www.pixiv.net/en/artworks/54711467

**Comment by NightLancer** [comment]
@drakom88 I downloaded last Chrome version and tested script there with your settings - all works fine for any count of artworks... From your description It looks like browser cache problem(I personally have 1GB cache with 20MB max entry caching, so 99% of my viewed arts fits in cache). 

[...] I found a quick solution for disabling cache and forcing browser to reload images every time and made a [temporary  version](https://pastebin.com/We91RdWk) of the script, you can try it. It is not the best solution, but cache problems is browser-related and options here are to increase cache size or disable it completely. 

Next time you encounter such a bug, open console(F12) with error logging("default levels" works just fine) and if there will be any errors - take screenshot of them and paste here, so I can know there is exactly script errors causing such an issue. Also such a screenshot from network tab with "img" selected when previewing the "error" images could help as well.
![зображення](https://user-images.githubusercontent.com/19971564/141203203-6a587fa2-f754-4991-b652-a9bbfbc69b72.png)

**Comment by drakom88** [comment]
Okay, I believe I increased the Chrome cache now. What is max entry caching?

The temporary version is showing a 404 error on the pastebin site.
I'm not well informed on what clearing cache affects, so these would be my major concerns with that method:
A) If I use that, or disable/reset cache will it delete the "Green followed" status for previously followed artists?
B) Will it disrupt saved entries for this script https://greasyfork.org/en/scripts/15173-visited-lite   ?

Thank you in advance if you have time to answer these concerns.

*edit*
Found one not working, hopefully these are what you requested.

![Untitled](https://user-images.githubusercontent.com/64705714/141213461-24ec374c-6d56-48dd-95d5-3cada36b57d0.png)

![Untitled 2](https://user-images.githubusercontent.com/64705714/141213667-b61330c0-c466-478c-b719-f55ba670b275.png)

**Comment by NightLancer** [comment]
@drakom88 fixed the link for the pastebin. 
You don't need to manually delete the cache. Not only it will delete all site data, but also doesn't affect browser caching system. Just try [modified](https://pastebin.com/We91RdWk) script version  and maybe it will help. 
> A) If I use that, or disable/reset cache will it delete the "Green followed" status for previously followed artists?

Specifically previously followed will be renewed after first start of the script, but all site data will be deleted(tags, history, some site settings)

> B) Will it disrupt saved entries for this script https://greasyfork.org/en/scripts/15173-visited-lite ?

Seems no, visited status is kept in browsers user profile and will be erased only if you creating new profile or wiping entire browser history(which also deletes not only history), but again it doesn't needed. 

> Found one not working, hopefully these are what you requested.

Yes, they are, but no script/cache errors present.

So, lets look if modified version of script will help.

**Comment by drakom88** [comment]
4 and 5 arts still not previewing after switching to new script.
I can deal with it if it's just my own problem, feel free to close as resolved if there are no easy fixes.
Thanks for the help and time!

**Comment by NightLancer** [comment]
@drakom88 meh, if it wasn't some caching problems then I don't know the reason... Seems like specific-condition problem(you also have doubling "false false" in settings menu which I don't [at any percentage and having same resolution], so something surely isn't right, but it's hard to tell what exactly).
Okay then, I will close this issue without resolved tag, and if someone else encounter same problem I hope they will see this one and comment here. 
The last thing I could advise is to try another browser(firefox/opera) just to test. I also have a plan to implement some backup storage for history so it will not be lost in such cases.
