### ISSUE TITLE
Idea- Toggleable option to hide followed and/or duplicate users.

### ISSUE THREAD

**Issue by drakom88** [NightLancer/PixivPreview#20]
Hello again =).
I was wondering if it would be possible for you to create a toggleable option to hide followed (and less importantly duplicate) profiles, especially in the "tags" section.
This would further greatly speed up my "workflow", and perhaps help others as well.

I found a script a while back to hide duplicate users, but it doesn't work as far as I can tell, and wouldn't apply to "tags" section anyway.
Thank you for your consideration; I will copy the script in case it's of any use. 
Feel free to close without comment if this is impossible/too difficult. My understanding on this subject is quite limited.

// ==UserScript==
// @name pixiv same author remover
// @description Removes same author when browsing related work below a submission in Pixiv
// @match https://www.pixiv.net/member_illust.php*
// @match https://www.pixiv.net/en/artworks/*
// @version 0.0.1.20200403073140
// @namespace https://greasyfork.org/users/301246
// ==/UserScript==

var main = function() {

  function filter() {

    var author = document.querySelectorAll('main + aside a[href*="/users/"]')[1];

    if (!author) {
      return; // not loaded
    }

    author = author.innerText;

    document.querySelectorAll('.gtm-illust-recommend-zone li').forEach(function(node) {
      var recAuthor = node.querySelector('.gtm-illust-recommend-user-name').innerText;
      if (recAuthor === author) {
        node.remove();
      }
    });
  }

  var loop = function() {
    filter();
    setTimeout(loop, 2000);
  };
  
  loop();
  
};

window.addEventListener('load', (event) => {
    main();
});

**Comment by NightLancer** [comment]
Hello @drakom88, I've made a quick update for search page according to your request.
 
Such feature was previously available on "discovery" page in 2.51, but after site layout update it was completely broken without any chance to restore on current layout, so I deleted it in 2.57. Hope this one will last for longer then 4 month)

**Comment by drakom88** [comment]
Very nice, but as usual not working for me >.<. 
The "Hide_Followed_Users" option toggle appears, but whether True or False green highlighting is disabled on "Tags" pages, and the option doesn't seem to have an effect on the "Discovery" page (but green highlighting works there).

*Edit*

Green highlighting on "Tags" pages isn't working on 3.73 or 3.50 either. I've reverted back to 3.10 where it does function.

**Comment by drakom88** [comment]
*edit* 
Green highlighted on "Tags" pages isn't working on 3.73 or 3.50 either. I've reverted back to 3.10 where it does function.

**Comment by NightLancer** [comment]
Well... I don't know what's wrong with all of this, I ran my script in Chrome and it worked. If you have some script errors in your console you need to paste them here so I have chance to see what is wrong. 

Pixiv don't have any announcements about "tags" page rework, so I suppose it must be the same as usual. Maybe you have another script that sorts artworks. Search page hasn't been affected in 3.50 version, it should work the same way. 

Discovery has whole new layout that can't be changed so much. Even If I hide some artworks(which will get look of minefield) they will be reloaded as soon as you scroll up/down, so there is no way this can be implemented in that page with current page engine.

**Comment by drakom88** [comment]
Thank you for looking into it, sorry for being a bother again.
So both highlighting and hide user works on "Tags" when I switch to another Chrome profile.
I've disabled other scripts and extensions, I will post console from both Chrome profiles.
If not an easy fix, I can switch profiles with only a bit of hassle.

Not working profile's console:
![Broken profile](https://user-images.githubusercontent.com/64705714/148983525-a8e46303-36bf-4f70-9922-0572d5cbd516.jpg)


Working profile's console:
![Working profile](https://user-images.githubusercontent.com/64705714/148983940-4dd99083-2444-468c-ab1e-f32d453c8227.jpg)

**Comment by drakom88** [comment]
Okay... now highlighting and hide users are working on my main profile after closing some tabs. Maybe I just had too many tabs open? At any rate, the "Hide followed" feature is perfect, thank you very much for reworking it!

*Edit*
Sorry, one more thing. I use zoom at 250%, and the preview sizes are large; could you create a couple of smaller preview size options (like 200 and 400 maybe) or some other fix? Thanks in advance for considering.

![Mysteriously working profile](https://user-images.githubusercontent.com/64705714/148986529-c48ca581-4744-4aab-9626-42d01fb678e2.jpg)

**Comment by drakom88** [comment]
The hide followed users is SO good, it's like magic. Thank you again x1000. Every new page I open I am grateful lol

**Comment by NightLancer** [comment]
Glad you liked it)

As for the smaller resolutions I think it's increase the time to quickly change the settings to another value, tho I'm personally keeping it at "auto" and switching only when testing updates that affects layout of previews. There is no 400px preview as I recall, and those are loading on new page actually already have 250px size, they just downscaled to the 184px by the css to fit into the page... So it's kinda not "bigger preview", but same picture with different scale. I don't really want to add such small preview, but maybe I reconsider it later.
