### ISSUE TITLE
Auto Pagination Load wrong page

### ISSUE THREAD

**Issue by HentaiRyuu** [NightLancer/PixivPreview#21]
Auto Pagination - Load next page
It just works as intended but it went wrong when look at artworks page with tag filter
It load normal artworks page **without** tag filter, but I want to it load with tag filter
so now, I have to disable **Auto Page** it when I want to use tag filter

Link for sample: https://www.pixiv.net/en/users/3618744/artworks/%E6%9D%B1%E6%96%B9

**Comment by NightLancer** [comment]
Hello. Yes, I've made that feature from zero and it may not work with all site functionality, adding tags support seems very possible, but I need to say that there may be conflicts with other scripts you are using if they modify your page URL(like adding own parameters). But since it's nice idea and you can always choose the scripts you want more at the moment – I'll look into adding this functionality.

**Comment by NightLancer** [comment]
Good news, I managed to implement tags support even without need of page reloading, which would've been very annoying in case of tags use.
_~~Order of bookmarked arts may be reversed – too hard to track all the variants(pixiv works differently for fist and next pages in general and for bookmarks particularly) – it's not very important as long as order of actual works is correct.~~_

**Comment by HentaiRyuu** [comment]
I tried new version, it seem you missing this part.
I don't know if I do it right but Change this
`let illustManga = illusts && 'illusts' || manga && 'manga';`
to this
`let illustManga = artworks && 'illustmanga' || illusts && 'illusts' || manga && 'manga';`

~~there also is weird problem
when you click after new page is loaded through auto pagination, all loaded illust just disappear~~
I just need to commented out this part for now
```
$('body').on('mouseup', 'a[href*="/illustrations/"], a[href*="/artworks/"], a[href*="/manga/"]', function(){
    let artsSection = getArtSectionContainers();
    [...artsSection.querySelectorAll('[style="display: flex;"]')].forEach(el => el.remove());
});
```

about reversed order, remove `.reverse()` from this line should fix
`Array.prototype.forEach.call(response.body?.thumbnails?.illust || Object.values(response.body.works).reverse(), (obj) => {`

**Comment by NightLancer** [comment]
Hello. Thanks for a quick reply. Unfortunately I've met some... unexpected force majeure circumstances and couldn't respond to you earlier. 

> I tried new version, it seem you missing this part.

Seems you're right. Fix will be in next update.

> there also is weird problem
> when you click after new page is loaded through auto pagination, all loaded illust just disappear

Uh, so eventually "cache" clearing doesn't work so well... Okay, I'll hotfix it with clunky `section>div>div>div>` selector for now(_still don't have much time to investigate this..._), but would appreciate any better idea with selecting tags for detecting they're being clicked without need to constantly check browser url(which may contain any arbitrary data with site updates/other scripts usage).

> about reversed order, remove `.reverse()` from this line should fix

Yes, it will fix tags processing order, but will break some "default" cases without them. Actually it is very annoying, 'cause pixiv has different response order even for same conditions for 1st and next pages, not saying that order differs on some illusts types as well. As I said earlier – I found tags order not so important atm, considering amount of efforts and code that needed to fix this order. Maybe later... 

Hope it'll work, did only quick tests, there may be some unexpected bugs left. If you meet some other bugs with it feel free to write about them here, I can't say when I will have opportunity to test it by myself properly...

**Comment by HentaiRyuu** [comment]
> Yes, it will fix tags processing order, but will break some "default" cases without them.

I just notice as you said, it break order in some case
so I just did some work around like this instead
```javascript
fetch(url).then(r => r.json()).then(response => {
  let fragment = new DocumentFragment();
  if (tags){
    Array.prototype.forEach.call(response.body?.thumbnails?.illust || Object.values(response.body.works), (obj) => {page(obj,art,fragment)});
  }else{
    Array.prototype.forEach.call(response.body?.thumbnails?.illust || Object.values(response.body.works).reverse(), (obj) => {page(obj,art,fragment)});
  }
  if (PAGETYPE==7 || tags) maxPageCount = Math.ceil(response.body.total/48);

  artsSection.appendChild(fragment);
  running = false;
});
```
Put this somewhere else (I put it under line 933 outside of bracket)
```javascript
function page(obj,art,fragment){
    let el = art.cloneNode(true);
    if (obj.pageCount > 1) [...(el.querySelectorAll('span'))].pop().textContent = obj.pageCount;
    else $(el.querySelector('span')).parents('a > div')[0].remove();
    //-----------------------------------------------------------------------
    let s = el.querySelector('[href]').href.match('/en/')?.[0] || '/';
    let hrefs = el.querySelectorAll('[href]');

    hrefs[0].setAttribute('data-gtm-value', obj.id);
    hrefs[0].href = s + "artworks/" + obj.id;

    hrefs[1].href = s + "artworks/" + obj.id;
    hrefs[1].textContent = obj.title;

    el.querySelector('img').src = obj.url;

    if (hrefs.length == 4){
        hrefs[2].setAttribute('data-gtm-value', obj.userId);
        hrefs[2].href = s + "users/" + obj.userId;

        hrefs[3].setAttribute('data-gtm-value', obj.userId);
        hrefs[3].href = s + "users/" + obj.userId;
        hrefs[3].textContent = obj.userName;

        el.querySelectorAll('img')[1].src = obj?.profileImageUrl || ''; //for deleted bookmarks
    }

    if (obj.bookmarkData) el.querySelectorAll('path:not(:only-child)').forEach(e => {
        e.setAttribute("style", "fill: rgb(255, 64, 96); !important")
    });
    //-----------------------------------------------------------------------
    el.style.display = "flex";
    fragment.appendChild(el);
}
```
