### ISSUE TITLE
Bug [3.83.3]: Click-to-preview not working

### ISSUE THREAD

**Issue by Chad90b** [NightLancer/PixivPreview#22]
hey nightlancer! hope you are doing well.

sorry to bring up another issue again, but lately the click-to-preview has not been working.

im now on the following versions:
Script version 3.83.3
Tampermonkey 4.16.1
Brave 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)
Windows, 10 Pro (Eng) (21H1 OSBuild 19043.1889) (64-bit)

issue description:
after changing setting to PREVIEW_ON_CLICK == FALSE and soft-refreshing the page, it will display the preview as expected

whenever PREVIEW_ON_CLICK == **TRUE** (and soft-refreshing) no preview is shown. clicking a thumb will open the page "normally" instead of showing the expected preview. it seems this is no longer working

*this has been tested will all extensions disabled (except for tampermonkey+script) and the results are identical*

**Comment by NightLancer** [comment]
@Chad90b Hello. Thanks for the report. Fixed.
Also as a bonus: now preview setting are applied immediately, without need to refresh the page.
