### ISSUE TITLE
Preview is only showing the first image, even on multi image albums

### ISSUE THREAD

**Issue by UmbraVivens** [NightLancer/PixivPreview#25]
example, post contains 15 images
![image](https://github.com/user-attachments/assets/11275db6-09f1-4821-b003-cd21b6ccc90e)
but preview only shows the first
![image](https://github.com/user-attachments/assets/d5926ecf-8b4e-4a6b-a86c-2cedacd556dc)

**Comment by subsubsubsubsubsub** [comment]
help ++++

**Comment by NightLancer** [comment]
@UmbraVivens @subsubsubsubsubsub should be fixed now.

**Comment by UmbraVivens** [comment]
confirmed working, thank you
