### ISSUE TITLE
Auto-Pagination is not working in the Following feed

### ISSUE THREAD

**Issue by UmbraVivens** [NightLancer/PixivPreview#26]
i made sure the script is up to date, i refreshed the tab and even reopened it, but it appears the Auto-Pagination feature stopped working when viewing the Following feed (http://www.pixiv.net/bookmark_new_illust.php)

**Comment by NightLancer** [comment]
Should've not been working on artists page too, fixed for both, thanks for notifying.

**Comment by UmbraVivens** [comment]
it seems this issue has returned

**Comment by NightLancer** [comment]
> it seems this issue has returned

Still works for me on both `bookmark_new_illust.php` and `/illustrations` pages, maybe they are testing some changes again.
On which pages it doesn't work at least and what script's error is in console?
![8cQABVH 1](https://github.com/user-attachments/assets/86916b67-b05c-4fc5-8ec9-61c40cbc376c)

**Comment by UmbraVivens** [comment]
oh sorry, the issue was back for one day and fixed on its own somehow, it's ok now
