### ISSUE TITLE
Preview block the original picture

### ISSUE THREAD

**Issue by s94285** [NightLancer/PixivPreview#3]
This issue cause me unable to click on link or add to favorite.
Add some shifting to the top will help.
This is what I did:
function setMangaHover(thisObj)
`var t=getOffsetRect(thisObj.parentNode.parentNode).top-((PAGETYPE==6)?thisObj.clientHeight:thisObj.parentNode.parentNode.clientHeight)*3;`
`mangaOuterContainer.style.top = ((t>150)?t-30:t+((PAGETYPE==6)?thisObj.clientHeight:thisObj.parentNode.parentNode.clientHeight)*4+100) +'px';`
function setHover(thisObj)
`var t=getOffsetRect(thisObj.parentNode.parentNode).top-((PAGETYPE==6)?thisObj.clientHeight:thisObj.parentNode.parentNode.clientHeight)*3;
      imgContainer.style.top = ((t>150)?t-30:t+((PAGETYPE==6)?thisObj.clientHeight:thisObj.parentNode.parentNode.clientHeight)*4+100)+'px';`

**Comment by NightLancer** [comment]
@s94285 I know that, I've thought that aligning to top left corner looks more beautifully. 
You current code gives preview shifts that can be out of visible area. And to hide it you must first move mouse from art to preview and then move it out, which is not so convenient(imho).
Besides, you can quickly add artwork to bookmarks by pressing Alt and then Left Mouse Button Click(without reloading or opening any new page). If you want to specify tags/privacy settings, repeat this combination again, and you will be on the current art tags editing page .
Is this solution not convenient for you?

**Comment by s94285** [comment]
I see. I used to open illustrate page to see more info, so I think I will stick to my code.
Didn't realize the purpose. Thank you for replying.
