### ISSUE TITLE
Prevent scrolling in parent window

### ISSUE THREAD

**Issue by MsgLosers** [NightLancer/PixivPreview#5]
Hello again NightLancer! Thank you for before when you added "click to preview" functionality. I am very grateful for all your work on this. :)

I was wondering, simply out of curiosity, if you think it would be necessary (and worth the time) to make the parent window non-scrollable while mouse is hovering inside the preview box? (I believe the term used for this is "Stop double-scrolling propagation").

Here is an example of it working pretty well (when you scroll the top box to the bottom, the bottom box does not scroll; it's locked in place until mouse cursor moves to the bottom box):
http://jsfiddle.net/4wrxq/272/

I ask because I notice that longer previews has a very long sideway-scroll and sometimes when I scroll too fast - or when we hit the end of the scroll - it scrolls down on the gallery page itself (in the background of the preview window). It's only a little bit frustrating and thought I would ask what you thought about any solution for it?

Thank you again for your time! :)

**Comment by NightLancer** [comment]
@MsgLosers Hello! Yeah, I've noticed those effect too, but it didn't frustrated me as much so I left it as is... You can update a fixed version from github [1.36.3](https://github.com/NightLancer/PixivPreview/blob/4c0928642346e2fc19c9478edeef468733e39bd2/PixivPreview.user.js) (and try other changes, such as profile card images preview, "similar users" bar[that appears after following a user] preview, and [if you set the flag] - some raw workspage restyle[I'm not done with it so I haven't posted it on gf yet])

**Comment by MsgLosers** [comment]
Hey @NightLancer oh that is super cool that you already have a version available with something of a fix. :} I'll give it a shot. Do you want feedback on it or nah?

**Comment by NightLancer** [comment]
@MsgLosers sure, you can leave a feedback. I'm already know about a bug with 1st-time preview of profile card arts, that follow suggestion bar preview extends beyond the page limits(I've currently softened this problem with scrollIntoView, but currently it is applies to every single preview case after following someone on the page... is this "ok", or it is annoying too?). 
And obviously you can tell if current manga preview scroll-bar behavior is that what you've expected?

**Comment by MsgLosers** [comment]
Hey @NightLancer 
Yeah I've seen a few oddities, but they are so rare that they're easily ignored for my part. So far, from what I've experienced, the new update is working **extremely well**. Thank you. The experience is fantastic. :)

Is it possible to use scrollIntoView with single-page preview, or only with multi-page/manga previews? Currently it only works for previews of multiple images. It's not an issue at all. I was just curious if it was on purpose? (and if you want to know, yes I would like to stop scrolling for all preview windows, even single image. but other people may have different preference I think) :)

Thanks again for your hard work! 👍 

I think the issue can easily be considered solved unless you will work more on it.

**Comment by NightLancer** [comment]
@MsgLosers Hi. I've found and fixed one of "oddities"(those with second-time manga previewing), fixed broken new-layout preview and added flag for scrolling propagation for manga, you can set it to `true` for your purposes.

> I was just curious if it was on purpose?

Yes, something like that. When I started to write this script I had 1366*768 monitor, and with `scrollIntoView` option the tall preview was often jerking up and down with every scroll.
But come to think of it, monitor with resolution lesser then fullhd must be something obsolete
in 2019, so I think I'll add scrollIntoView as default with option to revert it, and also add another flag to stop background scrolling by your request.

_p.s. almost uploaded a new version, but founded that pixiv has changed some page layout AGAIN, so my highlighting of followed users on illust page was broken, and I was needed to fix this sh~~ too-_-_

[1.36.7](https://greasyfork.org/uk/scripts/39387-pixiv-arts-preview-followed-atrists-coloring/code)

**Comment by MsgLosers** [comment]
> _p.s. almost uploaded a new version, but founded that pixiv has changed some page layout AGAIN, so my highlighting of followed users on illust page was broken, and I was needed to fix this sh~~ too-_-_

Oh my gosh! Thank you! I thought I was going crazy when it stopped working. My previous install did not update automatically; did you create a new script or something? Also if you don't mind, I would be grateful if you updated github version (I use your github page to update/install it).

Great work as always! Thanks for the fix!

**Comment by NightLancer** [comment]
> My previous install did not update automatically; did you create a new script or something?

I suppose, it may depend on the source you installed this script from for the first time. 
`downloadURL` is being deleted after uploading to the greacyfork (https://github.com/NightLancer/PixivPreview/raw/master/PixivPreview.user.js), and I don't surely know, by what url it is being replaced inside Tampermonkey/GreaceMonkey app (best guess - "https://greasyfork.org/scripts/39387-pixiv-arts-preview-followed-atrists-coloring/code/Pixiv%20Arts%20Preview%20%20Followed%20Atrists%20Coloring.user.js"), but it is works that way, so I don't worry much about it)

Ok, I'll keep in mind that there are may be users who installed my script firstly from github, not greacyfork, and 'll try to keep github version up to date too
[1.36.7 GitHub](https://github.com/NightLancer/PixivPreview/blob/master/PixivPreview.user.js)

p.s. If no objection/additions, I think I'd close this issue as solved.
