### ISSUE TITLE
some previews will not load

### ISSUE THREAD

**Issue by MsgLosers** [NightLancer/PixivPreview#7]
hey, not sure if this is a pixivpreview issue or not, but I wanted to ask you to get your opinion. i have noticed this image loading issue more and more often and as of late it happens so frequent that i can only view 2 previews before every other image shows this. only occurs for previews with multiple files (e.g. mangas)
![image](https://user-images.githubusercontent.com/41267032/73231289-46f06380-4180-11ea-950e-04b3aea7ec93.png)

any idea about this?

**Comment by NightLancer** [comment]
Hello. There were several updates that were not yet on GitHub, now they are. None of that directly affects multi-page loading, but maybe update will solve the problem?

I suppose, you is still using Chrome? Tampermonkey should work equally in Chrome and Firefox, but I have none problems in Firefox 73.0/Tampermonkey with latest script version (tested on [this](https://www.pixiv.net/en/users/11764388) page) Can you enable all info tabs in browsers debugging console and post here a screenshot of it when mulpitle image fails to load?

**Comment by NightLancer** [comment]
@MsgLosers any results?...

**Comment by MsgLosers** [comment]
> @MsgLosers any results?...

Hi, sorry for late reply! I ended up becoming very busy and I forgot to reply to you. Again I apologize; I did not mean to let you you wait so long.
I will make sure to check up on this and get back to you. Thank you for updating it on github too :)

**Comment by MsgLosers** [comment]
![image](https://user-images.githubusercontent.com/41267032/73697664-6b4bc300-46df-11ea-87c4-3ff75b52c077.png)

In the screenshot: Every line is shown before I click preview, except the 2 last red-colored lines. Those only appear after I click the preview. No other data. Anything else I can check?

EDIT: maybe this is useful too, so im posting it
![image](https://user-images.githubusercontent.com/41267032/73697782-bb2a8a00-46df-11ea-8dc3-914f5ae6878d.png)
![image](https://user-images.githubusercontent.com/41267032/73697823-d4333b00-46df-11ea-87bd-a80e33078ebb.png)

**Comment by NightLancer** [comment]
@MsgLosers Hi. Don't worry, all ok)

Thank you for provided screenshots. Judging by the error log, this happens on the search page. But I have no "custom-thumb" or "_custom1200" in on my search page, is there any possibility that you have premium account? There should be ajax call in the delevoper console after mouse click, like 
`GET https://www.pixiv.net/ajax/illust/79142617`. 
Can you give screenshot after several image-opening trying?

I've made a try for blind-fixing this issue  [1.44.2](https://github.com/NightLancer/PixivPreview/blob/master/PixivPreview.user.js). If that doesn't help – then I'll have to install your version of browser and script manager and try thing there(I'm using only FF and Opera now). 

Also, can you give me screenshot of settings you are using? And you may try this prefs, after trying update, to consider all the possibilities.
![](https://user-images.githubusercontent.com/19971564/73785074-4880e380-479f-11ea-8f6f-0d9c6d1eb868.png)

**Comment by MsgLosers** [comment]
I'll have to look closer at this to find out the AJAX calls you want. I'll try Firefox too, since that is more familiar to you. I'll also test the fix you provided, but first will try previous version in firefox; 1.44(.0) I'll get back to you later when I have the chance to test properly and gather info to you.

I don't have a premium account.

**Comment by MsgLosers** [comment]
@NightLancer Success!! 😄 👍 
1.44.2 fixes it.


I first tested Firefox with Greasemonkey (instead of Chrome/Tampermonkey). The initial script version 1.44.0 (from greasyfork.org directory) showed the same weird thumb-loading issue that only _sometimes_ occurred... So problem is seen when using version 1.44 and any browser and extension type so far.

I then tested the new 1.44.2 code you pushed to github and it works 100% better: No issue so far with thumb loading. I tested loading 6 pages of search results. All looks good now! Every thumb loaded 100% of the time. No 404-error this time.

I even tested with my old config settings, and it works:
![image](https://user-images.githubusercontent.com/41267032/73871785-c6e88e80-484e-11ea-9e55-8619539d0f7c.png)

I then added the 1.44.2 code to my Brave browser (Chromium based). It works here too. 👍 


Looks like your change in version 1.44.2 had a solution to the problem. Amazing job. I don't know how you found the problem with the little info I had in my issue post. :)
Was it a change Pixiv did? Their site changes very often now... 😭

**Comment by NightLancer** [comment]
@MsgLosers Glad to hear that!) 

> Looks like your change in version 1.44.2 had a solution to the problem. Amazing job. I don't know how you found the problem with the little info I had in my issue post. :)

=) I've spent a lot time in debugging, and this particulat bug turned out to be not so difficult after all.

> Was it a change Pixiv did? Their site changes very often now... sob

Perhaps. Yeah, that bring pain sometimes. But I'll try to keep up with site updates, especially when script-users give me an informative feedback)
