### ISSUE TITLE
me again, hehe, broken on the front page

### ISSUE THREAD

**Issue by MsgLosers** [NightLancer/PixivPreview#9]
Hey NightLancer, I hope you're doing well!

Sorry but its me again with more "pixiv is broken" issues :) Maybe they changed something on their site again, but the preview is not working on the frontpage (https://www.pixiv.net/en/) for example under "Recommended works". Clicking these just opens the page, no preview. Looks like they added some sort of language separation since the /en/ part so that could be it? I'm not sure.

Do you think its something you can look into again? :) Sorry for only asking for fixes!

**Comment by NightLancer** [comment]
Hello. Thank you for your concerning, I'm trying my best)

Yes, they've added page localization. But that's not a problem anymore, fixed)

No need for apologies, I'm always glad to receive a some feedback of my creation)

P.S. Worked this whole time on menu developing and designing(and design is my not strongest part, to be honest). But I did it! Check it out! (For now it is opens by the click on "Related services" icon).
![зображення](https://user-images.githubusercontent.com/19971564/77829601-bad0cd00-712b-11ea-8823-4f2cf968303e.png)

**Comment by MsgLosers** [comment]
Hey @NightLancer , thanks a whole ton for the update! :)

The new menu works great on the regular gallery and post pages, but not on the front-page sadly.

On the front page the menu does not appear and also you cannot preview any of the posts. Just to let you know. If I can help with debugging in any way, im here. :)

**Comment by NightLancer** [comment]
Thank your for feedback, I've made a fix using some help.

Now all should works fine(checked on all languages).
